/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sc_calculator_sajib;
import java.awt.Color;
import java.util.Stack;
import javax.swing.JButton;
import javax.swing.Timer;

/**
 *
 * @author Sajib
 * ID:232311314
 */
public class Sc_Calculator_sajib extends javax.swing.JFrame {

    private static int findNextOperator(String expression, int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form Sc_Calculator_Sajib
     */
    public Sc_Calculator_sajib() {
        initComponents();
        getContentPane().setBackground(new Color(128,128,128));
    }
    
    
    static String display="";
    static String a[]; 
    static String sign="";
    static double result=0;
    static double lastAnswer = 0;
    private boolean isCalculatorOn = false;  // Initially, the calculator is off

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        Dot = new javax.swing.JButton();
        Zero = new javax.swing.JButton();
        Ans = new javax.swing.JButton();
        Exp = new javax.swing.JButton();
        Equal = new javax.swing.JButton();
        Two = new javax.swing.JButton();
        One = new javax.swing.JButton();
        Plus = new javax.swing.JButton();
        Three = new javax.swing.JButton();
        Minus = new javax.swing.JButton();
        Seven = new javax.swing.JButton();
        Del = new javax.swing.JButton();
        Nine = new javax.swing.JButton();
        Five = new javax.swing.JButton();
        Ac = new javax.swing.JButton();
        Four = new javax.swing.JButton();
        Multiply = new javax.swing.JButton();
        Six = new javax.swing.JButton();
        Divide = new javax.swing.JButton();
        Eight = new javax.swing.JButton();
        Npr = new javax.swing.JButton();
        E = new javax.swing.JButton();
        Cos = new javax.swing.JButton();
        Ln = new javax.swing.JButton();
        Sin = new javax.swing.JButton();
        Xpower2 = new javax.swing.JButton();
        Tan = new javax.swing.JButton();
        Xinverse = new javax.swing.JButton();
        Sqrt = new javax.swing.JButton();
        Xpower3 = new javax.swing.JButton();
        XpowerN = new javax.swing.JButton();
        Sqrt3 = new javax.swing.JButton();
        Bracket_open = new javax.swing.JButton();
        Factorial = new javax.swing.JButton();
        Two_square = new javax.swing.JButton();
        Bracket_close = new javax.swing.JButton();
        Bin = new javax.swing.JButton();
        Pi = new javax.swing.JButton();
        Ncr = new javax.swing.JButton();
        Log = new javax.swing.JButton();
        Percentage = new javax.swing.JButton();
        Sin_in = new javax.swing.JButton();
        Tan_in = new javax.swing.JButton();
        Cos_in = new javax.swing.JButton();
        On_off = new javax.swing.JButton();
        Sqrt4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sajib's Calculator");

        jTextField1.setBackground(new java.awt.Color(204, 255, 204));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        Dot.setBackground(new java.awt.Color(204, 255, 255));
        Dot.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        Dot.setText("∙");
        Dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DotActionPerformed(evt);
            }
        });

        Zero.setBackground(new java.awt.Color(204, 255, 255));
        Zero.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        Zero.setText("0");
        Zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroActionPerformed(evt);
            }
        });

        Ans.setBackground(new java.awt.Color(153, 153, 153));
        Ans.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Ans.setText("Ans");
        Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsActionPerformed(evt);
            }
        });

        Exp.setBackground(new java.awt.Color(204, 255, 255));
        Exp.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        Exp.setText("EXP");
        Exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpActionPerformed(evt);
            }
        });

        Equal.setBackground(new java.awt.Color(153, 153, 153));
        Equal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Equal.setText("=");
        Equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualActionPerformed(evt);
            }
        });

        Two.setBackground(new java.awt.Color(204, 255, 255));
        Two.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        Two.setText("2");
        Two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoActionPerformed(evt);
            }
        });

        One.setBackground(new java.awt.Color(204, 255, 255));
        One.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        One.setText("1");
        One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneActionPerformed(evt);
            }
        });

        Plus.setBackground(new java.awt.Color(153, 153, 153));
        Plus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Plus.setText("+");
        Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusActionPerformed(evt);
            }
        });

        Three.setBackground(new java.awt.Color(204, 255, 255));
        Three.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        Three.setText("3");
        Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeActionPerformed(evt);
            }
        });

        Minus.setBackground(new java.awt.Color(153, 153, 153));
        Minus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Minus.setText("-");
        Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusActionPerformed(evt);
            }
        });

        Seven.setBackground(new java.awt.Color(204, 255, 255));
        Seven.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        Seven.setText("7");
        Seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenActionPerformed(evt);
            }
        });

        Del.setBackground(new java.awt.Color(255, 102, 51));
        Del.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Del.setText("DEL");
        Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelActionPerformed(evt);
            }
        });

        Nine.setBackground(new java.awt.Color(204, 255, 255));
        Nine.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        Nine.setText("9");
        Nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineActionPerformed(evt);
            }
        });

        Five.setBackground(new java.awt.Color(204, 255, 255));
        Five.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        Five.setText("5");
        Five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveActionPerformed(evt);
            }
        });

        Ac.setBackground(new java.awt.Color(255, 0, 51));
        Ac.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Ac.setText("AC");
        Ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcActionPerformed(evt);
            }
        });

        Four.setBackground(new java.awt.Color(204, 255, 255));
        Four.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        Four.setText("4");
        Four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourActionPerformed(evt);
            }
        });

        Multiply.setBackground(new java.awt.Color(153, 153, 153));
        Multiply.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Multiply.setText("×");
        Multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplyActionPerformed(evt);
            }
        });

        Six.setBackground(new java.awt.Color(204, 255, 255));
        Six.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        Six.setText("6");
        Six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixActionPerformed(evt);
            }
        });

        Divide.setBackground(new java.awt.Color(153, 153, 153));
        Divide.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Divide.setText("÷");
        Divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideActionPerformed(evt);
            }
        });

        Eight.setBackground(new java.awt.Color(204, 255, 255));
        Eight.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        Eight.setText("8");
        Eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightActionPerformed(evt);
            }
        });

        Npr.setBackground(new java.awt.Color(153, 153, 153));
        Npr.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Npr.setText("nPr");
        Npr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NprActionPerformed(evt);
            }
        });

        E.setBackground(new java.awt.Color(153, 153, 153));
        E.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        E.setText("e");
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });

        Cos.setBackground(new java.awt.Color(153, 153, 153));
        Cos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Cos.setText("cos");
        Cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosActionPerformed(evt);
            }
        });

        Ln.setBackground(new java.awt.Color(153, 153, 153));
        Ln.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Ln.setText("ln");
        Ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnActionPerformed(evt);
            }
        });

        Sin.setBackground(new java.awt.Color(153, 153, 153));
        Sin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Sin.setText("sin");
        Sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinActionPerformed(evt);
            }
        });

        Xpower2.setBackground(new java.awt.Color(153, 153, 153));
        Xpower2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Xpower2.setText("x²");
        Xpower2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Xpower2ActionPerformed(evt);
            }
        });

        Tan.setBackground(new java.awt.Color(153, 153, 153));
        Tan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Tan.setText("tan");
        Tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanActionPerformed(evt);
            }
        });

        Xinverse.setBackground(new java.awt.Color(153, 153, 153));
        Xinverse.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Xinverse.setText("1/x");
        Xinverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XinverseActionPerformed(evt);
            }
        });

        Sqrt.setBackground(new java.awt.Color(153, 153, 153));
        Sqrt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Sqrt.setText("√");
        Sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SqrtActionPerformed(evt);
            }
        });

        Xpower3.setBackground(new java.awt.Color(153, 153, 153));
        Xpower3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Xpower3.setText("x³");
        Xpower3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Xpower3ActionPerformed(evt);
            }
        });

        XpowerN.setBackground(new java.awt.Color(153, 153, 153));
        XpowerN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        XpowerN.setText("x^n");
        XpowerN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XpowerNActionPerformed(evt);
            }
        });

        Sqrt3.setBackground(new java.awt.Color(153, 153, 153));
        Sqrt3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Sqrt3.setText("³√");
        Sqrt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sqrt3ActionPerformed(evt);
            }
        });

        Bracket_open.setBackground(new java.awt.Color(153, 153, 153));
        Bracket_open.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Bracket_open.setText("(");
        Bracket_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bracket_openActionPerformed(evt);
            }
        });

        Factorial.setBackground(new java.awt.Color(153, 153, 153));
        Factorial.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Factorial.setText("!");
        Factorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FactorialActionPerformed(evt);
            }
        });

        Two_square.setBackground(new java.awt.Color(153, 153, 153));
        Two_square.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Two_square.setText("2^x");
        Two_square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Two_squareActionPerformed(evt);
            }
        });

        Bracket_close.setBackground(new java.awt.Color(153, 153, 153));
        Bracket_close.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Bracket_close.setText(")");
        Bracket_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bracket_closeActionPerformed(evt);
            }
        });

        Bin.setBackground(new java.awt.Color(204, 255, 255));
        Bin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Bin.setText("BIN");
        Bin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinActionPerformed(evt);
            }
        });

        Pi.setBackground(new java.awt.Color(153, 153, 153));
        Pi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Pi.setText("π");
        Pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiActionPerformed(evt);
            }
        });

        Ncr.setBackground(new java.awt.Color(153, 153, 153));
        Ncr.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Ncr.setText("nCr");
        Ncr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NcrActionPerformed(evt);
            }
        });

        Log.setBackground(new java.awt.Color(153, 153, 153));
        Log.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Log.setText("log");
        Log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogActionPerformed(evt);
            }
        });

        Percentage.setBackground(new java.awt.Color(153, 153, 153));
        Percentage.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Percentage.setText("%");
        Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PercentageActionPerformed(evt);
            }
        });

        Sin_in.setBackground(new java.awt.Color(153, 153, 153));
        Sin_in.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Sin_in.setText("cosec");
        Sin_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sin_inActionPerformed(evt);
            }
        });

        Tan_in.setBackground(new java.awt.Color(153, 153, 153));
        Tan_in.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Tan_in.setText("cot");
        Tan_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tan_inActionPerformed(evt);
            }
        });

        Cos_in.setBackground(new java.awt.Color(153, 153, 153));
        Cos_in.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Cos_in.setText("sec");
        Cos_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cos_inActionPerformed(evt);
            }
        });

        On_off.setBackground(new java.awt.Color(204, 255, 255));
        On_off.setText("");
        On_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                On_offActionPerformed(evt);
            }
        });

        Sqrt4.setBackground(new java.awt.Color(153, 153, 153));
        Sqrt4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Sqrt4.setText("|x|");
        Sqrt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sqrt4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel2.setText("Scientific Calculator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Seven, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Eight, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nine, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(Del, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ac, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Four, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Five, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Six, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(Multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(One, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Two, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Three, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Zero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Exp, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Xinverse, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Xpower2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Xpower3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(Sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Sqrt3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sqrt4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Pi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(XpowerN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(Log, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Ln, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Sin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Cos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Tan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Sin_in, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Cos_in, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tan_in, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Npr, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ncr, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bracket_open, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Bracket_close, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Two_square, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(On_off, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(On_off, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Sqrt3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Sqrt4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Xpower2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Xpower3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Xinverse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(XpowerN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Log, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ln, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sin_in, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tan_in, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cos_in, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bracket_open, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bracket_close, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ncr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Npr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Two_square, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eight, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nine, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Del, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Seven, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ac, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Five, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Six, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Four, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Two, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Three, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(One, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Zero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        getAccessibleContext().setAccessibleName("Sajib 's Calculator");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenActionPerformed
        // TODO add your handling code here:
        display=jTextField1.getText();
        jTextField1.setText(display+"7");
    }//GEN-LAST:event_SevenActionPerformed

    private void XinverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XinverseActionPerformed
        // TODO add your handling code here:
        display = jTextField1.getText();
        jTextField1.setText( display+"1/(" );
    }//GEN-LAST:event_XinverseActionPerformed

    private void ZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroActionPerformed
        display=jTextField1.getText();
        jTextField1.setText(display+"0");
    }//GEN-LAST:event_ZeroActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneActionPerformed
       
        display=jTextField1.getText();
        jTextField1.setText(display+"1");
    }//GEN-LAST:event_OneActionPerformed

    private void TwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoActionPerformed
       
        display=jTextField1.getText();
        jTextField1.setText(display+"2");
    }//GEN-LAST:event_TwoActionPerformed

    private void ThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeActionPerformed
       
        display=jTextField1.getText();
        jTextField1.setText(display+"3");
    }//GEN-LAST:event_ThreeActionPerformed

    private void FourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourActionPerformed
        // TODO add your handling code here:
        display=jTextField1.getText();
        jTextField1.setText(display+"4");
    }//GEN-LAST:event_FourActionPerformed

    private void FiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveActionPerformed
        // TODO add your handling code here:
        display=jTextField1.getText();
        jTextField1.setText(display+"5");
    }//GEN-LAST:event_FiveActionPerformed

    private void SixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixActionPerformed
    
        display=jTextField1.getText();
        jTextField1.setText(display+"6");
    }//GEN-LAST:event_SixActionPerformed

    private void EightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EightActionPerformed
       
        display=jTextField1.getText();
        jTextField1.setText(display+"8");
    }//GEN-LAST:event_EightActionPerformed

    private void NineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineActionPerformed
  
        display=jTextField1.getText();
        jTextField1.setText(display+"9");
    }//GEN-LAST:event_NineActionPerformed

    private void AcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcActionPerformed
        
        display="";
        jTextField1.setText(display+"");
        a=null; 
        sign="";
        result=0;
        
    }//GEN-LAST:event_AcActionPerformed

    private void AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsActionPerformed
      
            jTextField1.setText(String.valueOf(lastAnswer));
              
    }//GEN-LAST:event_AnsActionPerformed

    private void DotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DotActionPerformed
       display=jTextField1.getText();
        jTextField1.setText(display+".");
    }//GEN-LAST:event_DotActionPerformed

    private void ExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpActionPerformed
        // TODO add your handling code here:
        display=jTextField1.getText();
        jTextField1.setText(display+"E");
    }//GEN-LAST:event_ExpActionPerformed

    private void PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusActionPerformed
        // TODO add your handling code here:
        display=jTextField1.getText();
        jTextField1.setText(display+"+");
        sign=sign +"+";
    }//GEN-LAST:event_PlusActionPerformed

    private void MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusActionPerformed
       
        display=jTextField1.getText();
        jTextField1.setText(display+"-");

    }//GEN-LAST:event_MinusActionPerformed

    private void MultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplyActionPerformed
        
        display=jTextField1.getText();
        jTextField1.setText(display+"*");
        sign=sign +"*";
    }//GEN-LAST:event_MultiplyActionPerformed

    private void DivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideActionPerformed
      
        display=jTextField1.getText();
        jTextField1.setText(display+"/");
        sign=sign +"/";
    }//GEN-LAST:event_DivideActionPerformed

    private void DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelActionPerformed
     
        display=jTextField1.getText();
        display=display.substring(0,display.length()-1);
        jTextField1.setText(display);
    }//GEN-LAST:event_DelActionPerformed

    private void EqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualActionPerformed

                           try {
                                String expression = jTextField1.getText().trim();
                                String adjustedExpression = handleImplicitMultiplication(expression); // Preprocess
                                double result = evaluate(adjustedExpression); // Evaluate the adjusted expression
                                lastAnswer = result;
                                    jTextField1.setText(String.valueOf(result));
                                } catch (ArithmeticException e) {
                                    jTextField1.setText("Math Error: " + e.getMessage());
                                } catch (IllegalArgumentException e) {
                                    jTextField1.setText("Syntax Error: " + e.getMessage());
                                } catch (Exception e) {
                                    jTextField1.setText("Error");
                            }

        
    }//GEN-LAST:event_EqualActionPerformed

    
    
    
    
    private String handleImplicitMultiplication(String expression) {
    StringBuilder updatedExpression = new StringBuilder();
    for (int i = 0; i < expression.length(); i++) {
        char current = expression.charAt(i);
        updatedExpression.append(current);

        // Look ahead to the next character
        if (i < expression.length() - 1) {
            char next = expression.charAt(i + 1);

            // Case 1: Digit or closing parenthesis followed by an opening parenthesis
            if ((Character.isDigit(current) || current == ')') && next == '(') {
                updatedExpression.append('*');
            }
            // Case 2: Function (e.g., sin, cos) followed by a parenthesis
            if (Character.isLetter(current) && next == '(') {
                updatedExpression.append('*');
            }
        }
    }
    return updatedExpression.toString();
}

    
    
    
    
    
    
    
    
    
    
    
    private void Bracket_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bracket_openActionPerformed
      
        display = jTextField1.getText();
        jTextField1.setText(display + "(");
    }//GEN-LAST:event_Bracket_openActionPerformed

    private void Bracket_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bracket_closeActionPerformed
        
        display = jTextField1.getText();
        jTextField1.setText(display + ")");
    }//GEN-LAST:event_Bracket_closeActionPerformed

    private void FactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FactorialActionPerformed
        
        display = jTextField1.getText();
        jTextField1.setText(display + "!");
    }//GEN-LAST:event_FactorialActionPerformed

    private void TanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanActionPerformed
      
        display = jTextField1.getText();
        jTextField1.setText(display + "tan(");
    }//GEN-LAST:event_TanActionPerformed

    private void SinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinActionPerformed
     
        display = jTextField1.getText();
        jTextField1.setText(display + "sin(");
    }//GEN-LAST:event_SinActionPerformed

    private void CosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CosActionPerformed
       
        display = jTextField1.getText();
        jTextField1.setText(display + "cos(");
    }//GEN-LAST:event_CosActionPerformed

    private void NprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NprActionPerformed
        display = jTextField1.getText();
        jTextField1.setText(display + "P");
    }//GEN-LAST:event_NprActionPerformed

    private void NcrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NcrActionPerformed
        
        display = jTextField1.getText();
        jTextField1.setText(display + "C");
    }//GEN-LAST:event_NcrActionPerformed

    private void Xpower2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Xpower2ActionPerformed
        
        display = jTextField1.getText();
        jTextField1.setText(display + "^2");
    }//GEN-LAST:event_Xpower2ActionPerformed

    private void Xpower3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Xpower3ActionPerformed
       
        display = jTextField1.getText();
        jTextField1.setText(display + "^3");
    }//GEN-LAST:event_Xpower3ActionPerformed

    private void SqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SqrtActionPerformed
        
        display = jTextField1.getText();
        jTextField1.setText("√(" + display );
    }//GEN-LAST:event_SqrtActionPerformed

    private void Sqrt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sqrt3ActionPerformed
        // TODO add your handling code here:
        display = jTextField1.getText();
        jTextField1.setText("³√(" + display + ")");
    }//GEN-LAST:event_Sqrt3ActionPerformed

    private void LogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogActionPerformed
        
        display = jTextField1.getText();
        jTextField1.setText("log(" + display );
    }//GEN-LAST:event_LogActionPerformed

    private void LnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnActionPerformed
      
        display = jTextField1.getText();
        jTextField1.setText("ln(" + display );
    }//GEN-LAST:event_LnActionPerformed

    private void Two_squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Two_squareActionPerformed
        
        display = jTextField1.getText();
        jTextField1.setText("2^(" + display );
    }//GEN-LAST:event_Two_squareActionPerformed

    private void PercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PercentageActionPerformed
        
         display = jTextField1.getText();
        jTextField1.setText(display + "%");
    }//GEN-LAST:event_PercentageActionPerformed

    private void Sin_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sin_inActionPerformed
        display = jTextField1.getText();
        jTextField1.setText(display + "cosec(");
    }//GEN-LAST:event_Sin_inActionPerformed

    private void Tan_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tan_inActionPerformed
        display = jTextField1.getText();
    jTextField1.setText(display + "cot(");
    }//GEN-LAST:event_Tan_inActionPerformed

    private void Cos_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cos_inActionPerformed
        display = jTextField1.getText();
    jTextField1.setText(display + "sec(");
    }//GEN-LAST:event_Cos_inActionPerformed

    private void XpowerNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XpowerNActionPerformed
        
        display = jTextField1.getText();  
        jTextField1.setText(display + "^");  
    }//GEN-LAST:event_XpowerNActionPerformed

    private void PiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiActionPerformed
       
         display = jTextField1.getText();
         jTextField1.setText(display + "π");  // Append the π symbol to the text field
    }//GEN-LAST:event_PiActionPerformed

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        
        display = jTextField1.getText();
        jTextField1.setText(display + "e");
    }//GEN-LAST:event_EActionPerformed

    private void Sqrt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sqrt4ActionPerformed
        
        try {
            display = jTextField1.getText();
            double value = Double.parseDouble(display);
            jTextField1.setText(String.valueOf(Math.abs(value)));
        } catch (Exception e) {
            jTextField1.setText("Error");
        }
    }//GEN-LAST:event_Sqrt4ActionPerformed

    private void BinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinActionPerformed
        
        display = jTextField1.getText();
        jTextField1.setText(display + "Bin(");
    }//GEN-LAST:event_BinActionPerformed

    private void On_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_On_offActionPerformed
       
         if (isCalculatorOn) {
            // Turn off the calculator
            isCalculatorOn = false;
            
            // Set display text to "Sajib"
            jTextField1.setText("Sajib");
            
            // Disable text field and buttons (turn off the calculator)
            jTextField1.setEnabled(false);  // Disable the text field
            disableCalculatorButtons(true);  // Disable all calculator buttons
            
            // Change button text to show "Turn On"
            onOffButton.setText("Turn On");
        } else {
            // Turn on the calculator
            isCalculatorOn = true;
            
            // Set display text to "On"
            jTextField1.setText("");
            
            // Enable text field and buttons (turn on the calculator)
            jTextField1.setEnabled(true);  // Enable text field
            disableCalculatorButtons(false);  // Enable all calculator buttons
            
            // Change button text to show "Turn Off"
            onOffButton.setText("Turn Off");
        }
    }//GEN-LAST:event_On_offActionPerformed

    private void toggleCalculator(JButton onOffButton) {
    isCalculatorOn = !isCalculatorOn;
    if (isCalculatorOn) {
        // When the calculator is turned on
        jTextField1.setText("On");

        // Set a timer to clear the display after 1 second
        Timer timer = new Timer(0, e -> {
            jTextField1.setText("");  // Clear the display after 1 second
        });
        timer.setRepeats(false);  // Only run once
        timer.start();

        onOffButton.setText("Turn Off");  // Change the button text to "Turn Off"
    } else {
        // When the calculator is turned off
        jTextField1.setText("Sajib");
        inputText.setLength(0); // Clear the input text
        disableCalculatorButtons(true); // Disable all buttons
        onOffButton.setText("Turn On"); // Change the button text to "Turn On"
    }
}
    
    
                
        private void disableCalculatorButtons(boolean disable) {
             Ac.setEnabled(!disable);    
        Ans.setEnabled(!disable);
        Bin.setEnabled(!disable);
        Bracket_close.setEnabled(!disable);
        Bracket_open.setEnabled(!disable);
        Cos.setEnabled(!disable);
        Cos_in.setEnabled(!disable);
        Del.setEnabled(!disable);
        Divide.setEnabled(!disable);
        Dot.setEnabled(!disable);
        E.setEnabled(!disable);
        Eight.setEnabled(!disable);
        Equal.setEnabled(!disable);
        Exp.setEnabled(!disable);
        Factorial.setEnabled(!disable);
        Five.setEnabled(!disable);
        Four.setEnabled(!disable);
        Ln.setEnabled(!disable);
        Log.setEnabled(!disable);
        Minus.setEnabled(!disable);
        Sqrt4.setEnabled(!disable);
        Multiply.setEnabled(!disable);
        Ncr.setEnabled(!disable);
        Nine.setEnabled(!disable);
        Npr.setEnabled(!disable);
//        On_off.setEnabled(!disable);
        One.setEnabled(!disable);
        Percentage.setEnabled(!disable);
        Pi.setEnabled(!disable);
        Plus.setEnabled(!disable);
        Seven.setEnabled(!disable);
        Sin.setEnabled(!disable);
        Sin_in.setEnabled(!disable);
        Six.setEnabled(!disable);
        Sqrt.setEnabled(!disable);
        Sqrt3.setEnabled(!disable);
        Tan.setEnabled(!disable);
        Tan_in.setEnabled(!disable);
        Three.setEnabled(!disable);
        Two.setEnabled(!disable);
        Two_square.setEnabled(!disable);
        Xinverse.setEnabled(!disable);
        Xpower2.setEnabled(!disable);
         Xpower3.setEnabled(!disable);
        XpowerN.setEnabled(!disable);
        Zero.setEnabled(!disable);

    }
    
    
    
            
           private static int precedence(char operator) {
            switch (operator) {
                case '+':
                case '-': return 1;
                case '*':
                case '/': return 2;
                case '%': return 2;
                case '^': return 3; // Exponentiation has higher precedence
                default: return -1;
            }
        }

        private static boolean isOperator(char c) {
            return c == '+' || c == '-' || c == '*' || c == '/' || c == '%' || c == '^';
        }

        private static double applyOperation(char operator, double b, double a) {
            switch (operator) {
                case '+': return a + b;
                case '-': return a - b;
                case '*': return a * b;
                case '/': 
                    if (b == 0) throw new ArithmeticException("Cannot divide by zero");
                    return a / b;
                case '%': return a % b;
                case '^': return Math.pow(a, b); // Power operation
                default: throw new IllegalArgumentException("Invalid operator");
            }
        }
 
            
            
            
            
        private static double evaluate(String expression) {
            
          // Stacks for numbers and operators
          if (expression.startsWith("-")) {
               expression = "0" + expression; // Prepend "0" to handle the negative start
          }
          
           expression = expression.trim();
        if (expression.isEmpty()) {
            throw new IllegalArgumentException("Invalid expression: Expression cannot be empty.");
        }




        
        
if (expression.startsWith("Bin(") && expression.endsWith(")")) {
        String inside = expression.substring(4, expression.length() - 1).trim();
        double result = evaluate(inside); // Evaluate inside Bin(...)
        
        // Ensure the result is an integer for binary conversion
        if (result % 1 != 0) {
            throw new IllegalArgumentException("Binary conversion requires an integer.");
        }
        String binaryResult = Integer.toBinaryString((int) result);
        return Double.parseDouble(binaryResult);  // Convert binary string back to decimal
    }
    if (expression.startsWith("sin(") && expression.endsWith(")")) {
        String inside = expression.substring(4, expression.length() - 1).trim();
        double result = evaluate(inside);
        return Math.sin(Math.toRadians(result));  // Convert to radians before applying sin()
    }

    if (expression.startsWith("cos(") && expression.endsWith(")")) {
        String inside = expression.substring(4, expression.length() - 1).trim();
        double result = evaluate(inside);
        
        // Handle cos(90), cos(270), etc. correctly (it should return 0)
        if (result % 360 == 90 || result % 360 == 270) {
            return 0;  // cos(90) or cos(270) is 0
        }
        return Math.cos(Math.toRadians(result));  // Convert to radians before applying cos()
    }

    if (expression.startsWith("tan(") && expression.endsWith(")")) {
        String inside = expression.substring(4, expression.length() - 1).trim();
        double result = evaluate(inside);
        
        // Check for values where tan(x) goes to infinity (like 90, 270, etc.)
        if (result % 180 == 90) {  // tan(90), tan(270), tan(450), etc. go to infinity
            throw new ArithmeticException("tan(" + result + ") is undefined (infinity).");
        }
        return Math.tan(Math.toRadians(result)); // Convert to radians before applying tan()
    }

            if (expression.startsWith("cosec(") && expression.endsWith(")")) {
            String inside = expression.substring(6, expression.length() - 1).trim();
            double value = evaluate(inside); // Evaluate the argument
            double sineValue = Math.sin(Math.toRadians(value)); // sin(x) in radians
            if (Math.abs(sineValue) < 1e-10) { // Avoid division by zero with a small tolerance
                throw new ArithmeticException("cosec(" + value + ") is undefined.");
            }
            return 1 / sineValue; // Return cosec(x)
            }


            if (expression.startsWith("sec(") && expression.endsWith(")")) {
            String inside = expression.substring(4, expression.length() - 1).trim();
            double value = evaluate(inside); // Evaluate the argument
            double cosineValue = Math.cos(Math.toRadians(value)); // cos(x) in radians
            if (Math.abs(cosineValue) < 1e-10) { // Avoid division by zero with a small tolerance
                throw new ArithmeticException("sec(" + value + ") is undefined.");
            }
            return 1 / cosineValue; // Return sec(x)
            }



        if (expression.startsWith("cot(") && expression.endsWith(")")) {
        // Extract the value inside cot(...)
        String inside = expression.substring(4, expression.length() - 1).trim();
        double value = evaluate(inside); // Recursively evaluate the argument inside cot()

        // Normalize the angle to handle periodicity
        value = value % 360;
        if (value < 0) {
            value += 360; // Ensure the angle is positive
        }

        // Handle special cases for cot(x)
        if (value == 90 || value == 270) {
            return Double.POSITIVE_INFINITY; // cot(90) and cot(270) are infinity
        }

        if (value % 180 == 0) { // cot(0), cot(180), cot(360), etc. are undefined
            throw new ArithmeticException("cot(" + value + ") is undefined.");
        }

        // Regular computation for cot(x)
        double tangentValue = Math.tan(Math.toRadians(value));
        if (Math.abs(tangentValue) < 1e-10) { // Handle near-zero tan(x)
            throw new ArithmeticException("cot(" + value + ") is undefined.");
        }
        return 1 / tangentValue; // Compute cot(x) = 1 / tan(x)
    }

        


        // Handle 'nP' for permutations (nPr)
        if (expression.contains("P")) {
            int pIndex = expression.indexOf("P");
            double r = Double.parseDouble(expression.substring(pIndex + 1));
            double n = Double.parseDouble(expression.substring(0, pIndex));
            return nPr((int) n, (int) r);
        }

        // Handle 'nC' for combinations (nCr)
        if (expression.contains("C")) {
            int cIndex = expression.indexOf("C");
            double r = Double.parseDouble(expression.substring(cIndex + 1));
            double n = Double.parseDouble(expression.substring(0, cIndex));
            return nCr((int) n, (int) r);
        }
        if (expression.contains("E")) {
        String[] parts = expression.split("E");
        if (parts.length == 2) {
            double base = evaluate(parts[0]); 
            double exponent = evaluate(parts[1]); 
            return base * Math.pow(10, exponent);
        }
        }
        if (expression.contains("^2")) {
        int idx = expression.indexOf("^2");
        double value = evaluate(expression.substring(0, idx));
        return value * value;
        }
        if (expression.contains("^3")) {
        int idx = expression.indexOf("^3");
        double value = evaluate(expression.substring(0, idx)); // Get the base
        return value * value * value; // Calculate x^3
    }
        
        
        
        
       

    
    if (expression.contains("2^")) {
        int idx = expression.indexOf("2^");
        double exponent = evaluate(expression.substring(idx + 2)); // Get the exponent
        return Math.pow(2, exponent); // 2 raised to the power of x
    }

    if (expression.contains("^")) {
        int idx = expression.indexOf("^");
        double base = evaluate(expression.substring(0, idx)); // Get the base
        double exponent = evaluate(expression.substring(idx + 1)); // Get the exponent
        return Math.pow(base, exponent); // Calculate x^n
    }
    
    
    
    
    if (expression.startsWith("Bin(") && expression.endsWith(")")) {
        // Extract the argument inside "Bin(...)"
        String inside = expression.substring(4, expression.length() - 1).trim();

        // Evaluate the argument recursively
        double result = evaluate(inside);

        // Ensure the result is an integer for binary conversion
        if (result % 1 != 0) {
            throw new IllegalArgumentException("Binary conversion requires an integer.");
        }

        // Return the binary result as a decimal equivalent (for display in text field)
        String binaryResult = Integer.toBinaryString((int) result);
        System.out.println("Binary result: " + binaryResult); // Debugging
        return Double.parseDouble(binaryResult); // Convert binary string back to decimal
    }
    
    
    
          
          Stack<Double> numbers = new Stack<>();
          Stack<Character> operators = new Stack<>();

          for (int i = 0; i < expression.length(); i++) {
              char c = expression.charAt(i);

              // Handle numbers
              if (Character.isDigit(c) || c == '.') {
                  StringBuilder number = new StringBuilder();

                  while (i < expression.length() && (Character.isDigit(expression.charAt(i)) || expression.charAt(i) == '.')) {
                      number.append(expression.charAt(i));
                      i++;
                  }
                  i--; // Step back for loop increment
                  numbers.push(Double.parseDouble(number.toString()));
              }  else if (expression.startsWith("log(", i)) {
            int endIndex = findClosingParenthesis(expression, i + 3);
            double value = evaluate(expression.substring(i + 4, endIndex)); // Exclude "log("
            if (value <= 0) throw new ArithmeticException("Logarithm undefined for non-positive numbers");
            numbers.push(Math.log10(value)); // Logarithm base 10
            i = endIndex;

        // Handle 'ln' (natural logarithm)
        } else if (expression.startsWith("ln(", i)) {
            int endIndex = findClosingParenthesis(expression, i + 2);
            double value = evaluate(expression.substring(i + 3, endIndex)); // Exclude "ln("
            if (value <= 0) throw new ArithmeticException("Natural logarithm undefined for non-positive numbers");
            numbers.push(Math.log(value)); // Natural logarithm (base e)
            i = endIndex;

        // Handle trigonometric and other functions (e.g., sin, cos, tan)
        } else if (expression.startsWith("sin(", i)) {
            int endIndex = findClosingParenthesis(expression, i + 3);
            double value = evaluate(expression.substring(i + 4, endIndex));
            numbers.push(Math.sin(Math.toRadians(value)));
            i = endIndex;
        } else if (expression.startsWith("cos(", i)) {
            int endIndex = findClosingParenthesis(expression, i + 3);
            double value = evaluate(expression.substring(i + 4, endIndex));
            numbers.push(Math.cos(Math.toRadians(value)));
            i = endIndex;
        } else if (expression.startsWith("tan(", i)) {
            int endIndex = findClosingParenthesis(expression, i + 3);
            double value = evaluate(expression.substring(i + 4, endIndex));
            numbers.push(Math.tan(Math.toRadians(value)));
            i = endIndex;

        // Handle other operations (e.g., sin⁻¹, cos⁻¹, tan⁻¹, etc.)
        } else if (expression.startsWith("sin⁻¹(", i)) {
            int endIndex = findClosingParenthesis(expression, i + 5);
            double value = evaluate(expression.substring(i + 5, endIndex));
            numbers.push(Math.toDegrees(Math.asin(value)));
            i = endIndex;
        } else if (expression.startsWith("cos⁻¹(", i)) {
            int endIndex = findClosingParenthesis(expression, i + 5);
            double value = evaluate(expression.substring(i + 5, endIndex));
            numbers.push(Math.toDegrees(Math.acos(value)));
            i = endIndex;
        } else if (expression.startsWith("tan⁻¹(", i)) {
            int endIndex = findClosingParenthesis(expression, i + 5);
            double value = evaluate(expression.substring(i + 5, endIndex));
            numbers.push(Math.toDegrees(Math.atan(value)));
            i = endIndex;

        // Handle operators
        }  else if (expression.startsWith("1/(", i)) {
            int endIndex = findClosingParenthesis(expression, i + 2);
            double value = evaluate(expression.substring(i + 2, endIndex));
            numbers.push(1 / value);
            i = endIndex;
        } else if (expression.startsWith("π", i)) {
            numbers.push(Math.PI);
        } else if (expression.startsWith("e", i)) {
            numbers.push(Math.E);
        }
              else if (expression.startsWith("1/(", i)) {
                int endIndex = findClosingParenthesis(expression, i + 2);
                double value = evaluate(expression.substring(i + 2, endIndex));
                numbers.push(1 / value);
                i = endIndex;
            }else if (expression.startsWith("√(", i)) {
            int endIndex = findClosingParenthesis(expression, i + 1);
            double value = evaluate(expression.substring(i + 2, endIndex)); // Exclude "√("
            numbers.push(Math.sqrt(value)); // Calculate square root
            i = endIndex;

       
        } else if (expression.startsWith("³√(", i)) {
            int endIndex = findClosingParenthesis(expression, i + 2);
            double value = evaluate(expression.substring(i + 3, endIndex)); // Exclude "³√("
            numbers.push(Math.cbrt(value)); // Calculate cube root
            i = endIndex;

        
        } else if (expression.startsWith("log(", i)) {
                int endIndex = findClosingParenthesis(expression, i + 3);
                double value = evaluate(expression.substring(i + 3, endIndex));
                numbers.push(Math.log10(value));
                i = endIndex;
            } else if (expression.startsWith("ln(", i)) {
                int endIndex = findClosingParenthesis(expression, i + 2);
                double value = evaluate(expression.substring(i + 2, endIndex));
                numbers.push(Math.log(value));
                i = endIndex;
            }else if (expression.startsWith("P", i)) {
            int endIndex = i + 1;
            double r = numbers.pop();
            double n = numbers.pop();
            numbers.push(nPr((int) n, (int) r)); // Calculate nPr
            i = endIndex;

        // Handle 'nC' for combinations (nCr)
        } else if (expression.startsWith("C", i)) {
            int endIndex = i + 1;
            double r = numbers.pop();
            double n = numbers.pop();
            numbers.push(nCr((int) n, (int) r)); // Calculate nCr
            i = endIndex;

        // Handle 'log' (logarithm base 10)
        }else if (c == '%') {
            double value = numbers.pop();
            numbers.push(value / 100); // Percentage is the number divided by 100

            // Handle factorial (!)
            }else if (c == '!') {
                // The previous number should be factorialized
            double value = numbers.pop();
            if (value != (int) value || value < 0) {
                throw new ArithmeticException("Factorial is only defined for non-negative integers");
            }
            numbers.push(factorial((int) value));

        // Handle opening parenthesis
        }
              else if (c == '(') {
                  // Handle opening parenthesis
                  operators.push(c);
              } else if (c == ')') {
                  // Handle closing parenthesis
                  while (!operators.isEmpty() && operators.peek() != '(') {
                      numbers.push(applyOperation(operators.pop(), numbers.pop(), numbers.pop()));
                  }
                  operators.pop(); // Remove '('
              } else if (isOperator(c)) {
                  // Handle operators based on precedence
                  while (!operators.isEmpty() && precedence(c) <= precedence(operators.peek())) {
                      numbers.push(applyOperation(operators.pop(), numbers.pop(), numbers.pop()));
                  }
                  operators.push(c);
              } 
          }

          // Process remaining operators
          while (!operators.isEmpty()) {
              numbers.push(applyOperation(operators.pop(), numbers.pop(), numbers.pop()));
          }

          return numbers.pop();
      }
            
            
            private static int findClosingParenthesis(String expression, int startIndex) {
                int balance = 0;
                for (int i = startIndex; i < expression.length(); i++) {
                    if (expression.charAt(i) == '(') {
                        balance++;
                    } else if (expression.charAt(i) == ')') {
                        balance--;
                        if (balance == 0) {
                            return i;
                        }
                    }
                }
                return -1; // If no closing parenthesis is found
            }
            
            


           
            private static double factorial(int n) {
                if (n < 0) throw new IllegalArgumentException("Factorial undefined for negative numbers");
                double result = 1;
                for (int i = 1; i <= n; i++) {
                    result *= i;
                }
                return result;
            }

            // Permutation (nPr)
            private static double nPr(int n, int r) {
                if(r>n) throw new IllegalArgumentException("r can't be greater than n.");
                return factorial(n) / factorial(n - r);
            }

            // Combination (nCr)
            private static double nCr(int n, int r) {
                if(r>n) throw new IllegalArgumentException("r can't be greater than n.");
                return factorial(n) / (factorial(r) * factorial(n - r));
            }
  
                  
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sc_Calculator_sajib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sc_Calculator_sajib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sc_Calculator_sajib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sc_Calculator_sajib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sc_Calculator_sajib().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ac;
    private javax.swing.JButton Ans;
    private javax.swing.JButton Bin;
    private javax.swing.JButton Bracket_close;
    private javax.swing.JButton Bracket_open;
    private javax.swing.JButton Cos;
    private javax.swing.JButton Cos_in;
    private javax.swing.JButton Del;
    private javax.swing.JButton Divide;
    private javax.swing.JButton Dot;
    private javax.swing.JButton E;
    private javax.swing.JButton Eight;
    private javax.swing.JButton Equal;
    private javax.swing.JButton Exp;
    private javax.swing.JButton Factorial;
    private javax.swing.JButton Five;
    private javax.swing.JButton Four;
    private javax.swing.JButton Ln;
    private javax.swing.JButton Log;
    private javax.swing.JButton Minus;
    private javax.swing.JButton Multiply;
    private javax.swing.JButton Ncr;
    private javax.swing.JButton Nine;
    private javax.swing.JButton Npr;
    private javax.swing.JButton On_off;
    private javax.swing.JButton One;
    private javax.swing.JButton Percentage;
    private javax.swing.JButton Pi;
    private javax.swing.JButton Plus;
    private javax.swing.JButton Seven;
    private javax.swing.JButton Sin;
    private javax.swing.JButton Sin_in;
    private javax.swing.JButton Six;
    private javax.swing.JButton Sqrt;
    private javax.swing.JButton Sqrt3;
    private javax.swing.JButton Sqrt4;
    private javax.swing.JButton Tan;
    private javax.swing.JButton Tan_in;
    private javax.swing.JButton Three;
    private javax.swing.JButton Two;
    private javax.swing.JButton Two_square;
    private javax.swing.JButton Xinverse;
    private javax.swing.JButton Xpower2;
    private javax.swing.JButton Xpower3;
    private javax.swing.JButton XpowerN;
    private javax.swing.JButton Zero;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
